services:
  gh-page:
    build: 
      context: .
      args:
        NODE_ENV: development
    restart: on-failure
    ports:
      - 8080:3000
    volumes:
      - .:/home/node/app:rw
      - /home/node/app/node_modules
      - /home/node/app/.astro